# Generated by Django 4.0.5 on 2022-06-19 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursosapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='time',
            new_name='date',
        ),
    ]
